### PR TITLE
Enable containers 0.7 (ghc 9.10)

### PR DESCRIPTION
**Pull request by edsko**

### CODE REVIEW

**Review by kazu-yamamoto — CHANGES_REQUESTED** [review]
I guess it's better to remove the upper bound in this case.

**Comment by edsko** [comment]
I don't understand..?

**Comment by edsko** [comment]
I mean, I can remove the upper bound if you like, or set it to something really high (otherwise Hackage will not accept the package at all), but it's not an automatic given that `http2` will continue to work with each new major version (which, by definition, can introduce breaking changes)?

**Comment by kazu-yamamoto** [comment]
I have suffered from the major version up of `bytestring`.
My packages do not hit the breaking changes but I needed to modify their cabal files.
I guess that `containers` follows the same pattern.
So, I would like to simply remove the upper bound.

**Comment by edsko** [comment]
Removing the upper bound altogether will cause Hackage to reject the package. Will I set it to `>= 0.6 < 1`, similar to what you do with base (`>= 4.9 < 5`)?

**Comment by kazu-yamamoto** [comment]
I would like to remove the upper bound only for `containers`.
I don't think the change results in a reject from Hackage.
But you don't like this approach, `>= 0.6 < 1` is acceptable.

**Comment by edsko** [comment]
Oh, maybe you are right, I just checked, and it's a warning only...? :thinking: Only if it is `base` it is an actual reject..? Ok, I learned something new today :) Will fix.

**Review by kazu-yamamoto — APPROVED** [review]
Now LGTM

**Comment by kazu-yamamoto** [comment]
Rebased and merged.

**Pull request closed without merging**
