### PR TITLE
Support bytestring-0.11

### PR DESCRIPTION
**Pull request by Bodigrim**
Similar to https://github.com/kazu-yamamoto/network-byte-order/pull/2, If this looks too involved, alternatively you can just drop support of GHC 7.10 with a revision: for GHC 8.0+ `bytestring-0.11` provides a backward compatible pattern synonym `PS`. **Upd.:** But in such scenario earlier releases need to be revised with `bytestring < 0.11`, otherwise `cabal` will choose to build them and choke. 

It would be nice to share `withBS` between `Network.HPACK.Huffman.ByteString` and `Network.HPACK.Token`, but I'm not sure where to put such compatibility module.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
@Bodigrim Should I do the same thing as `fast-logger`?

**Comment by Bodigrim** [comment]
Yes, please.

**Comment by kazu-yamamoto** [comment]
Done. Would you check?

**Comment by Bodigrim** [comment]
Perfect, thanks!

**Comment by kazu-yamamoto** [comment]
@Bodigrim Are there any issues which I can help?

**Comment by Bodigrim** [comment]
I did not review thoroughly everything; I guess the latest changes should cut off the majority of invalid build plans already.

One random observation: https://github.com/kazu-yamamoto/http-date/blob/24d1a00435a6c31f474503bf3754fa1bffe7b9bb/Network/HTTP/Date/Formatter.hs#L80 need to use http://hackage.haskell.org/package/bytestring-0.11.1.0/docs/Data-ByteString-Internal.html#v:toForeignPtr instead of pattern-matching. This is backwards compatible, no CPP needed.

**Comment by kazu-yamamoto** [comment]
@Bodigrim Thank you for pointing out. I would like to drop the support of GHC 7 in `http-date`. In this case, should I do the same thing as others to `http-date`?

**Comment by Bodigrim** [comment]
Yes, I think so.

**Pull request closed without merging**
