### PR TITLE
Avoid unnecessary empty data frames at end of stream

### PR DESCRIPTION
**Pull request by FinleyMcIlwaine**
If a stream terminates with an empty data frame, we will send that empty data frame even if it is succeeded by trailers that are marked end of stream. That empty data frame is unnecessary. We should only send it if the payload length is non-zero and we are not sending trailers.

I discovered this after seeing `too many empty data` errors from terminating a server handling several concurrent streams with an exception.

### CODE REVIEW

**Comment by FinleyMcIlwaine** [comment]
I cannot reproduce the current test failure locally after running the test on a loop for a while, on my branch or on `main`. My guess is that it is a non-deterministic failure that is not associated with these changes.

**Review by kazu-yamamoto — APPROVED** [review]
Nice catch!

**Comment by kazu-yamamoto** [comment]
It seems to me that your logic is correct.
So, rebased and merged.
Thanks.

**Comment by FinleyMcIlwaine** [comment]
@kazu-yamamoto Thanks for that! Also, we have another PR incoming soon, so don't worry about releasing these changes just yet.

**Comment by kazu-yamamoto** [comment]
The previous release was for me.
I needed to deploy the new `ServerIO` for my project.

**Pull request closed without merging**
