### PR TITLE
New server arch

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
This implements #127

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Test fails sometime.
This failure should be fixed with #102.

**Comment by kazu-yamamoto** [comment]
@khibino Even with this PR, `bowline` can work well.

**Comment by edsko** [comment]
If I update my dependencies to use this new version of `http2`, without changing anything else, my test suite fails. I will investigate why.

**Comment by edsko** [comment]
All my tests simply deadlock. I will try to figure out where and why.

**Comment by kazu-yamamoto** [comment]
Thank you but I don't want you to take time to understand the deadlock at this moment.
I know the current code is unstable a bit.
I should at least resolve #102.
For this purpose, I'm now labeling all threads so that `listThreads` gives me much information.

**Comment by edsko** [comment]
Ok, then I shall wait :) FWIW, it seems that the client can connect to the server just fine, and the server can respond, and the client gets the initial response headers, but then the (streaming) response body is never started, and the client is left waiting.

**Comment by kazu-yamamoto** [comment]
If you run `h2c-client` and `h2c-server`, they list up the current threads with their status per second. :)

**Comment by kazu-yamamoto** [comment]
@edsko It would be nice if you tested the current `main`.

**Comment by edsko** [comment]
@kazu-yamamoto I just tried with 80de8dbf9e20c93dc72feab600166c9b2aa7addd , same result as with aa6f979146033629121a54964e258c3a611fed7a . My test setup is that the client does a streaming request to the server; this request arrives, and the serves initiates a streaming response. The client receives the headers, but then nothing. If I insert a call to `putStrLn` in `outBodyPush` at https://github.com/kazu-yamamoto/http2/blob/80de8dbf9e20c93dc72feab600166c9b2aa7addd/Network/HTTP2/Server/Worker.hs#L150 then I can see that print statement executed with the data that the client _should_ receive, but the client does not receive anything after the response headers. There is a Wireshark log at https://github.com/well-typed/grapesy/pull/183 where we're tracking updating to the new `http2` architecture.

**Comment by kazu-yamamoto** [comment]
@edsko I cannot reproduce your issue.
If you kindly inserted several `putStrLn`s into `Sender.hs`, you could see what's happening.

**Pull request merged**
