### PR TITLE
Improve documentation of the `authority` field

### PR DESCRIPTION
**Pull request by edsko**
Very minor PR that just improves documentation (part of an attempt to clarify the exact situation in https://github.com/kazu-yamamoto/http2-tls/pull/6).

### CODE REVIEW

**Comment by edsko** [comment]
@kazu-yamamoto Ok, this is now correct, best I can tell. I will leave some additional comments on the `http2-tls` PR, but I think this is good to merge.

In the haddock I have used `@authority` rather than `'authority'` to the field of `ClientConfig`, because if I do the latter, `haddock` renders that as `ClientConfig` rather than as `authority` for some reason.

**Comment by edsko** [comment]
(Possibly related to the haddock thing: https://github.com/haskell/haddock/issues/1608 . But not a huge deal for this PR of course.)

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged.
Thank you!

**Pull request merged**
